---
title: "Schedule"
slug: schedule
---

```{r include=FALSE}
library(tidyverse)
library(calendar)
library(lubridate)
library(glue)
library(rvest)

strip_html <- function(s) {
  html_text(read_html(charToRaw(s)))
}

schedule_raw <- yaml::read_yaml(here::here("data", "schedule.yaml"))$lessons

schedule_df <- enframe(schedule_raw) %>% 
  mutate(cleaned = map(value, ~as.data.frame(.))) %>% 
  unnest(cleaned) %>% 
  filter(is.na(header)) %>% 
  select(-value, -bg, -bottomborder, -header)

class_year <- "2021"
base_url <- "https://datavizs21.classes.andrewheiss.com/"
content_base <- glue("{base_url}content/")
assignment_base <- glue("{base_url}assignment/")
schedule_ics_path <- "schedule/schedule.ics"
ics_url <- glue(base_url, schedule_ics_path)

schedule_clean <- schedule_df %>%
  mutate(title = map_chr(title, strip_html)) %>%
  mutate(session_clean = ifelse(is.na(session), "", glue("({session}) "))) %>% 
  mutate(summary = glue("PMAP 8521: {session_clean}{title}")) %>% 
  mutate(date_start = ifelse(is.na(date_start), date, date_start),
         date_end = ifelse(is.na(date_end), date, date_end)) %>% 
  mutate(date_start = glue("{date_start}, {class_year}"),
         date_end = glue("{date_end}, {class_year}")) %>% 
  mutate(date_start_actual = map(date_start, ~as.POSIXct(., format = "%B %d, %Y")),
         date_end_actual = map(date_end, ~as.POSIXct(., format = "%B %d, %Y"))) %>% 
  mutate(content = ifelse(!is.na(content), glue("{content_base}{content}/"), NA),
         assignment = ifelse(!is.na(assignment), glue("{assignment_base}{assignment}/"), NA)) %>% 
  mutate(url = coalesce(content, assignment),
         url = ifelse(is.na(url), "", url))

schedule_ics <- schedule_clean %>% 
  group_by(name) %>% 
  nest() %>% 
  mutate(ical = map(data,
                    ~ic_event(start = .$date_start_actual[[1]],
                              end = .$date_end_actual[[1]] + 24*60*60,
                              summary = .$summary[[1]],
                              more_properties = TRUE,
                              event_properties = c("DESCRIPTION" = .$url[[1]])))) %>% 
  ungroup() %>% 
  select(-name, -data) %>% 
  unnest(ical) %>% 
  ical() %>% 
  rename(`DTSTART;VALUE=DATE` = DTSTART,
         `DTEND;VALUE=DATE` = DTEND)

ic_write(schedule_ics, here::here("content", "schedule", "schedule.ics"))
```

Here's your roadmap for the semester!

Every class session has four important sections. You should read about the details for each using the main menu at the top of this webpage.

- [**Content**](/content/) (<i class="fas fa-book-reader"></i>): This page contains the readings, slides, and recorded lectures for the topic. Read and watch these first each day.
- [**Lesson**](/lesson/) (<i class="fas fa-chalkboard-teacher"></i>): This page contains an interactive lesson that teaches you the principles and code you need to know. Go through these after doing the content.
- [**Example**](/example/) (<i class="fas fa-laptop-code"></i>): This page contains fully annotated R code that you can use as a reference for creating your own visualizations. This is only a reference page—you don't have to necessarily do anything here. Each section also contains videos of me live coding the examples so you can see what it looks like to work with R in real time. This page will be *very* helpful as you work on your assignments.
- [**Assignment**](/assignment/) (<i class="fas fa-pencil-ruler"></i>): This page contains the instructions for either the session exercise (1–3 brief tasks), or for the two mini projects and final project. **Assignments are due by 11:59 PM on the Monday after their corresponding sessions.** That's confusing in sentence form—see the schedule table below to see how it works.

:::note
**tl;dr**: You should follow this general process for each session:

- Do everything on the content (<i class="fas fa-book-reader"></i>) page
- Work through the lesson (<i class="fas fa-chalkboard-teacher"></i>) page
- Complete the assignment (<i class="fas fa-pencil-ruler"></i>) while referencing the example (<i class="fas fa-laptop-code"></i>)
:::

<div class="ical">
You can subscribe to this calendar URL in Outlook, Google Calendar, or Apple Calendar:<br><a class="btn btn-primary" href="/`r schedule_ics_path`" role="button"><i class="far fa-calendar-alt"></i></a> <input id="ics_url" type="text" value="`r ics_url`" onclick="this.select()" readonly="readonly" size="60" />
</div>

---

`r blogdown::shortcode("schedule")`
